### ISSUE TITLE
Failing Python tests

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#112]
@jfowkes @nimgould (#87) 
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/gls/Python/test_gls.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/gls/Python/test_gls.py", line 21, in <module>
    options = gls.initialize(solver)
TypeError: galahad.gls.initialize() takes no arguments (1 given)
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/trs/Python/test_trs.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/trs/Python/test_trs.py", line 1, in <module>
    from galahad import trs
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/trs.cpython-310-x86_64-linux-gnu.so: undefined symbol: sls_make_options_dict
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/fdc/Python/test_fdc.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/fdc/Python/test_fdc.py", line 1, in <module>
    from galahad import fdc
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/fdc.cpython-310-x86_64-linux-gnu.so: undefined symbol: sls_make_options_dict
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/rqs/Python/test_rqs.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/rqs/Python/test_rqs.py", line 1, in <module>
    from galahad import rqs
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/rqs.cpython-310-x86_64-linux-gnu.so: undefined symbol: sls_make_options_dict
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/bqp/Python/test_bqp.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/bqp/Python/test_bqp.py", line 1, in <module>
    from galahad import bqp
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/bqp.cpython-310-x86_64-linux-gnu.so: undefined symbol: sbls_update_control
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/cqp/Python/test_cqp.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/cqp/Python/test_cqp.py", line 1, in <module>
    from galahad import cqp
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/cqp.cpython-310-x86_64-linux-gnu.so: undefined symbol: sbls_update_control
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/dqp/Python/test_dqp.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/dqp/Python/test_dqp.py", line 1, in <module>
    from galahad import dqp
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/dqp.cpython-310-x86_64-linux-gnu.so: undefined symbol: sbls_update_control
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/dps/Python/test_dps.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/dps/Python/test_dps.py", line 1, in <module>
    from galahad import dps
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/dps.cpython-310-x86_64-linux-gnu.so: undefined symbol: sls_make_options_dict
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/eqp/Python/test_eqp.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/eqp/Python/test_eqp.py", line 1, in <module>
    from galahad import eqp
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/eqp.cpython-310-x86_64-linux-gnu.so: undefined symbol: sbls_update_control
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/bgo/Python/test_bgo.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/bgo/Python/test_bgo.py", line 1, in <module>
    from galahad import bgo
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/bgo.cpython-310-x86_64-linux-gnu.so: undefined symbol: ugo_make_options_dict
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/bgo/Python/test_bgo_quadratic.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/bgo/Python/test_bgo_quadratic.py", line 1, in <module>
    from galahad import bgo
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/bgo.cpython-310-x86_64-linux-gnu.so: undefined symbol: ugo_make_options_dict
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/nls/Python/test_nls.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/nls/Python/test_nls.py", line 1, in <module>
    from galahad import nls
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/nls.cpython-310-x86_64-linux-gnu.so: undefined symbol: psls_make_inform_dict
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/dgo/Python/test_dgo.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/dgo/Python/test_dgo.py", line 1, in <module>
    from galahad import dgo
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/dgo.cpython-310-x86_64-linux-gnu.so: undefined symbol: ugo_make_options_dict
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/dgo/Python/test_dgo_quadratic.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/dgo/Python/test_dgo_quadratic.py", line 1, in <module>
    from galahad import dgo
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/dgo.cpython-310-x86_64-linux-gnu.so: undefined symbol: ugo_make_options_dict
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/bqpb/Python/test_bqpb.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/bqpb/Python/test_bqpb.py", line 1, in <module>
    from galahad import bqpb
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/bqpb.cpython-310-x86_64-linux-gnu.so: undefined symbol: sbls_update_control
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/lpb/Python/test_lpb.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/lpb/Python/test_lpb.py", line 1, in <module>
    from galahad import lpb
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/lpb.cpython-310-x86_64-linux-gnu.so: undefined symbol: sbls_update_control
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/lsqp/Python/test_lsqp.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/lsqp/Python/test_lsqp.py", line 1, in <module>
    from galahad import lsqp
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/lsqp.cpython-310-x86_64-linux-gnu.so: undefined symbol: sbls_update_control
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/qpa/Python/test_qpa.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/qpa/Python/test_qpa.py", line 1, in <module>
    from galahad import qpa
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/qpa.cpython-310-x86_64-linux-gnu.so: undefined symbol: sls_make_options_dict
```
```shell
alexis@HP-Spectre:~$ /usr/bin/python3 /home/alexis/Bureau/git/GALAHAD/builddir_python/../src/qpb/Python/test_qpb.py
Traceback (most recent call last):
  File "/home/alexis/Bureau/git/GALAHAD/builddir_python/../src/qpb/Python/test_qpb.py", line 1, in <module>
    from galahad import qpb
ImportError: /home/alexis/.local/lib/python3.10/site-packages/galahad/qpb.cpython-310-x86_64-linux-gnu.so: undefined symbol: sbls_update_control
```

**Comment by amontoison** [comment]
fixed by #162
