### ISSUE TITLE
Errors in sls and sbls tests with the MUMPS linear solver

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#122]
```
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir_mumps$ ./sblst_single

 error exit tests 

 test   status
    3       -3
   15      -26

 basic tests of storage formats 

        storage prec fact  new   status residual
       IDENTITY   -1    1    2        0     tiny
       IDENTITY   -1    1    1        0     tiny
       IDENTITY   -1    1    0        0     tiny
SCALED_IDENTITY   -1    1    2        0     tiny
SCALED_IDENTITY   -1    1    1        0     tiny
SCALED_IDENTITY   -1    1    0        0     tiny
       DIAGONAL   -1    1    2        0     tiny
       DIAGONAL   -1    1    1        0     tiny
       DIAGONAL   -1    1    0        0     tiny
          DENSE   -1    1    2        0     tiny
          DENSE   -1    1    1        0     tiny
          DENSE   -1    1    0        0     tiny
 SPARSE_BY_ROWS   -1    1    2        0     tiny
 SPARSE_BY_ROWS   -1    1    1        0     tiny
 SPARSE_BY_ROWS   -1    1    0        0     tiny
     COORDINATE   -1    1    2        0     tiny
     COORDINATE   -1    1    1        0     tiny
     COORDINATE   -1    1    0        0     tiny
       IDENTITY   -1    2    2        0     tiny
       IDENTITY   -1    2    1        0     tiny
       IDENTITY   -1    2    0        0     tiny
SCALED_IDENTITY   -1    2    2        0     tiny
SCALED_IDENTITY   -1    2    1        0     tiny
SCALED_IDENTITY   -1    2    0        0     tiny
       DIAGONAL   -1    2    2        0     tiny
       DIAGONAL   -1    2    1        0     tiny
       DIAGONAL   -1    2    0        0     tiny
          DENSE   -1    2    2        0     tiny
          DENSE   -1    2    1        0     tiny
          DENSE   -1    2    0        0     tiny
 SPARSE_BY_ROWS   -1    2    2        0     tiny
 SPARSE_BY_ROWS   -1    2    1        0     tiny
 SPARSE_BY_ROWS   -1    2    0        0     tiny
     COORDINATE   -1    2    2        0     tiny
     COORDINATE   -1    2    1        0     tiny
     COORDINATE   -1    2    0        0     tiny

 basic tests of symmetric linear solvers 

    <---  solver  --->
    definite  symmetric  status residual
      sils      sils      -26
      ma57      ma57      -26
      ma77      ma77      -26
      ma86      ma86      -26
      ma87     ssids      -26
      ma97      ma97       -9
   pardiso   pardiso       -9
mkl_pardismkl_pardis       -9
      wsmp      wsmp       -9
    pastix    pastix      -26
      potr      sytr        0     tiny
      sytr      sytr        0     tiny
     ssids     ssids      -26

 basic tests of unsymmetric linear solvers 

    solver   status residual
       gls      -13
      ma48      -13
      getr        0     tiny

 basic tests of options 

 test   status residual

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f117e023ad0 in ???
#1  0x7f117e022c35 in ???
#2  0x7f117dc4251f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7f117f993d48 in __galahad_sls_single_MOD_sls_solve_ir
	at ../src/sls/sls.F90:5603
#4  0x7f117f878dff in __galahad_sbls_single_MOD_sbls_solve_explicit
	at ../src/sbls/sbls.F90:5351
#5  0x7f117f87bdbb in __galahad_sbls_single_MOD_sbls_solve
	at ../src/sbls/sbls.F90:5145
#6  0x55730fb27052 in galahad_sbls_example
	at ../src/sbls/sblst.F90:699
#7  0x55730fb2e1c1 in main
	at ../src/sbls/sblst.F90:4
Erreur de segmentation (core dumped)
```
```
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir_mumps$ ./sblst_double

 error exit tests 

 test   status
    3       -3
   15      -26

 basic tests of storage formats 

        storage prec fact  new   status residual
       IDENTITY   -1    1    2        0     tiny
       IDENTITY   -1    1    1        0     tiny
       IDENTITY   -1    1    0        0     tiny
SCALED_IDENTITY   -1    1    2        0     tiny
SCALED_IDENTITY   -1    1    1        0     tiny
SCALED_IDENTITY   -1    1    0        0     tiny
       DIAGONAL   -1    1    2        0     tiny
       DIAGONAL   -1    1    1        0     tiny
       DIAGONAL   -1    1    0        0     tiny
          DENSE   -1    1    2        0     tiny
          DENSE   -1    1    1        0     tiny
          DENSE   -1    1    0        0     tiny
 SPARSE_BY_ROWS   -1    1    2        0     tiny
 SPARSE_BY_ROWS   -1    1    1        0     tiny
 SPARSE_BY_ROWS   -1    1    0        0     tiny
     COORDINATE   -1    1    2        0     tiny
     COORDINATE   -1    1    1        0     tiny
     COORDINATE   -1    1    0        0     tiny
       IDENTITY   -1    2    2        0     tiny
       IDENTITY   -1    2    1        0     tiny
       IDENTITY   -1    2    0        0     tiny
SCALED_IDENTITY   -1    2    2        0     tiny
SCALED_IDENTITY   -1    2    1        0     tiny
SCALED_IDENTITY   -1    2    0        0     tiny
       DIAGONAL   -1    2    2        0     tiny
       DIAGONAL   -1    2    1        0     tiny
       DIAGONAL   -1    2    0        0     tiny
          DENSE   -1    2    2        0     tiny
          DENSE   -1    2    1        0     tiny
          DENSE   -1    2    0        0     tiny
 SPARSE_BY_ROWS   -1    2    2        0     tiny
 SPARSE_BY_ROWS   -1    2    1        0     tiny
 SPARSE_BY_ROWS   -1    2    0        0     tiny
     COORDINATE   -1    2    2        0     tiny
     COORDINATE   -1    2    1        0     tiny
     COORDINATE   -1    2    0        0     tiny

 basic tests of symmetric linear solvers 

    <---  solver  --->
    definite  symmetric  status residual
      sils      sils      -26
      ma57      ma57      -26
      ma77      ma77      -26
      ma86      ma86      -26
      ma87     ssids      -26
      ma97      ma97       -9
   pardiso   pardiso       -9
mkl_pardismkl_pardis       -9
      wsmp      wsmp       -9
    pastix    pastix      -26
      potr      sytr        0     tiny
      sytr      sytr        0     tiny
     ssids     ssids      -26

 basic tests of unsymmetric linear solvers 

    solver   status residual
       gls      -13
      ma48      -13
      getr        0     tiny

 basic tests of options 

 test   status residual

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f6e9fa23ad0 in ???
#1  0x7f6e9fa22c35 in ???
#2  0x7f6e9f64251f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7f6ea139cb52 in __galahad_sls_double_MOD_sls_solve_ir
	at ../src/sls/sls.F90:5603
#4  0x7f6ea1281377 in __galahad_sbls_double_MOD_sbls_solve_explicit
	at ../src/sbls/sbls.F90:5351
#5  0x7f6ea1284363 in __galahad_sbls_double_MOD_sbls_solve
	at ../src/sbls/sbls.F90:5145
#6  0x56213227b05a in galahad_sbls_example
	at ../src/sbls/sblst.F90:699
#7  0x5621322821c9 in main
	at ../src/sbls/sblst.F90:4
Erreur de segmentation (core dumped)
```
```
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir_mumps$ ./slst_single
 coordinate storage 
  default ordering
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso   fail   fail       fail       fail     fail 
         wsmp   none 
       pastix   none 
        mumps   none 
         potr    ok      ok        ok         ok       ok  
         sytr    ok      ok        ok         ok       ok  
         pbtr    ok      ok        ok         ok       ok  
        ssids   none 
  computed ordering
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso   fail   fail  
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f4860623ad0 in ???
#1  0x7f4860622c35 in ???
#2  0x7f486024251f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7f48602a179f in unlink_chunk
	at ./malloc/malloc.c:1628
#4  0x7f48602a46aa in _int_malloc
	at ./malloc/malloc.c:4307
#5  0x7f48602a51b8 in __GI___libc_malloc
	at ./malloc/malloc.c:3329
#6  0x7f483e623ca7 in ???
#7  0x7f483db8992d in ???
#8  0x7f4840147f71 in ???
#9  0x7f484014fbae in ???
#10  0x7f484015f84d in ???
#11  0x7f483fe46321 in ???
#12  0x7f4840117923 in ???
#13  0x7f485ecf939a in ???
#14  0x7f4861f88606 in sls_solve_multiple_rhs
	at ../src/sls/sls.F90:6705
#15  0x7f4861f8f965 in __galahad_sls_single_MOD_sls_solve_ir_multiple
	at ../src/sls/sls.F90:5880
#16  0x55f205ea9ceb in galahad_sls_test_program
	at ../src/sls/slst.F90:298
#17  0x55f205eb12c3 in main
	at ../src/sls/slst.F90:6
Erreur de segmentation (core dumped)
```
```
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir_mumps$ ./slst_double
 coordinate storage 
  default ordering
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso    ok      ok        ok         ok       ok  
         wsmp   none 
       pastix   none 
        mumps   none 
         potr    ok      ok        ok         ok       ok  
         sytr    ok      ok        ok         ok       ok  
         pbtr    ok      ok        ok         ok       ok  
        ssids   none 
  computed ordering
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso    ok      ok        ok         ok       ok  
         wsmp   none 
       pastix   none 
        mumps   none 
         potr    ok      ok        ok         ok       ok  
         sytr    ok      ok        ok         ok       ok  
         pbtr   none 
        ssids   none 
  provided ordering
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso    ok      ok        ok         ok       ok  
         wsmp   none 
       pastix   none 
        mumps   none 
         potr    ok      ok        ok         ok       ok  
         sytr    ok      ok        ok         ok       ok  
         pbtr    ok      ok        ok         ok       ok  
        ssids   none 
  MC64 scaling
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso   ordering unavailable 
         wsmp   none 
       pastix   none 
        mumps   none 
         potr   ordering unavailable 
         sytr   ordering unavailable 
         pbtr   ordering unavailable 
        ssids   none 
  MC77 1-norm scaling
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso   ordering unavailable 
         wsmp   none 
       pastix   none 
        mumps   none 
         potr   ordering unavailable 
         sytr   ordering unavailable 
         pbtr   ordering unavailable 
        ssids   none 
  MC77 infinity-norm scaling
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso   ordering unavailable 
         wsmp   none 
       pastix   none 
        mumps   none 
         potr   ordering unavailable 
         sytr   ordering unavailable 
         pbtr   ordering unavailable 
        ssids   none 
 sparse by rows storage 
  default ordering
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso    ok      ok        ok         ok       ok  
         wsmp   none 
       pastix   none 
        mumps   none 
         potr    ok      ok        ok         ok       ok  
         sytr    ok      ok        ok         ok       ok  
         pbtr    ok      ok        ok         ok       ok  
        ssids   none 
  computed ordering
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso    ok      ok        ok         ok       ok  
         wsmp   none 
       pastix   none 
        mumps   none 
         potr    ok      ok        ok         ok       ok  
         sytr    ok      ok        ok         ok       ok  
         pbtr   none 
        ssids   none 
  provided ordering
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso    ok      ok        ok         ok       ok  
         wsmp   none 
       pastix   none 
        mumps   none 
         potr    ok      ok        ok         ok       ok  
         sytr    ok      ok        ok         ok       ok  
         pbtr    ok      ok        ok         ok       ok  
        ssids   none 
  MC64 scaling
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso   ordering unavailable 
         wsmp   none 
       pastix   none 
        mumps   none 
         potr   ordering unavailable 
         sytr   ordering unavailable 
         pbtr   ordering unavailable 
        ssids   none 
  MC77 1-norm scaling
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso   ordering unavailable 
         wsmp   none 
       pastix   none 
        mumps   none 
         potr   ordering unavailable 
         sytr   ordering unavailable 
         pbtr   ordering unavailable 
        ssids   none 
  MC77 infinity-norm scaling
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso   ordering unavailable 
         wsmp   none 
       pastix   none 
        mumps   none 
         potr   ordering unavailable 
         sytr   ordering unavailable 
         pbtr   ordering unavailable 
        ssids   none 
 dense storage 
  default ordering
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso    ok      ok        ok         ok       ok  
         wsmp   none 
       pastix   none 
        mumps   none 
         potr    ok      ok        ok         ok       ok  
         sytr    ok      ok        ok         ok       ok  
         pbtr    ok      ok        ok         ok       ok  
        ssids   none 
  computed ordering
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso    ok      ok        ok         ok       ok  
         wsmp   none 
       pastix   none 
        mumps   none 
         potr    ok      ok        ok         ok       ok  
         sytr    ok      ok        ok         ok       ok  
         pbtr   none 
        ssids   none 
  provided ordering
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso    ok      ok        ok         ok       ok  
         wsmp   none 
       pastix   none 
        mumps   none 
         potr    ok      ok        ok         ok       ok  
         sytr    ok      ok        ok         ok       ok  
         pbtr    ok      ok        ok         ok       ok  
        ssids   none 
  MC64 scaling
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso   ordering unavailable 
         wsmp   none 
       pastix   none 
        mumps   none 
         potr   ordering unavailable 
         sytr   ordering unavailable 
         pbtr   ordering unavailable 
        ssids   none 
  MC77 1-norm scaling
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso   ordering unavailable 
         wsmp   none 
       pastix   none 
        mumps   none 
         potr   ordering unavailable 
         sytr   ordering unavailable 
         pbtr   ordering unavailable 
        ssids   none 
  MC77 infinity-norm scaling
       solver  1 RHS  1 refine  >1 RHS    >1 refine  partial
         sils   none 
         ma57   none 
         ma77   none 
         ma86   none 
         ma87   none 
         ma97   none 
      pardiso   none 
  mkl_pardiso   ordering unavailable 
         wsmp   none 
       pastix   none 
        mumps   none 
         potr   ordering unavailable 
         sytr   ordering unavailable 
         pbtr   ordering unavailable 
        ssids   none 
 error tests
       solver     -3   -20   -31   -26
         sils    -26   -26   -39
         ma57    -26   -26   -39
         ma77     -3   -26   -39
         ma86     -3   -26   -39
         ma87     -3   -26   -39
         ma97     -3   -26   -39
      pardiso     -3   -29   -39
  mkl_pardiso     -3   -37   -39
         wsmp     -3   -29   -39
       pastix    -26   -26   -39
        mumps    -26free(): invalid next size (fast)

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7f3566c23ad0 in ???
#1  0x7f3566c22c35 in ???
#2  0x7f356684251f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7f3566896a7c in __pthread_kill_implementation
	at ./nptl/pthread_kill.c:44
#4  0x7f3566896a7c in __pthread_kill_internal
	at ./nptl/pthread_kill.c:78
#5  0x7f3566896a7c in __GI___pthread_kill
	at ./nptl/pthread_kill.c:89
#6  0x7f3566842475 in __GI_raise
	at ../sysdeps/posix/raise.c:26
#7  0x7f35668287f2 in __GI_abort
	at ./stdlib/abort.c:79
#8  0x7f35668896f5 in __libc_message
	at ../sysdeps/posix/libc_fatal.c:155
#9  0x7f35668a0d7b in malloc_printerr
	at ./malloc/malloc.c:5664
#10  0x7f35668a2b1c in _int_free
	at ./malloc/malloc.c:4522
#11  0x7f35668a54d2 in __GI___libc_free
	at ./malloc/malloc.c:3391
#12  0x7f35685cf520 in __galahad_space_double_MOD_space_dealloc_integer_pointer
	at ../src/space/space.F90:3705
#13  0x7f356858dbf7 in __galahad_sls_double_MOD_sls_terminate
	at ../src/sls/sls.F90:7137
#14  0x55b55dd69145 in galahad_sls_test_program
	at ../src/sls/slst.F90:682
#15  0x55b55dd6a51f in main
	at ../src/sls/slst.F90:6
Abandon (core dumped)
```

**Comment by amontoison** [comment]
We don't have anymore this error in #185.
I close the issue.
