### ISSUE TITLE
Segmentation fault with LANCELOT B tests

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#14]
@nimgould 
```shell
alexis@HP-Spectre:~/Bureau/git/GALAHAD/src$ make -s -f $GALAHAD/makefiles/$arch test
 Compiling lancelott      		[ OK ]

 Exhaustive test of subroutine interface to LANCELOT B

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f139b87bad0 in ???
#1  0x7f139b87ac35 in ???
#2  0x7f139b58b51f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x5601e5f0835c in ???
#4  0x5601e5eb5bbe in ???
#5  0x5601e5ece111 in ???
#6  0x5601e5ea6350 in ???
#7  0x5601e5eaa7d3 in ???
#8  0x7f139b572d8f in __libc_start_call_main
	at ../sysdeps/nptl/libc_start_call_main.h:58
#9  0x7f139b572e3f in __libc_start_main_impl
	at ../csu/libc-start.c:392
#10  0x5601e5ea22f4 in ???
#11  0xffffffffffffffff in ???
Segmentation fault (core dumped)
 Tests for LANCELOT B complete
```

**Comment by nimgould** [comment]
I don't see this here. Which platform? Could you recompile with e.g, DEBUG = -g -fbacktrace
in $GALAHAD/makefiles/(architecture) for your architecture, i.e.
cd $GALAHAD/src/lancelot
make -s -f (architecrure) cleanall
make -s -f (architecrure) test
and report back. Thank you

**Comment by amontoison** [comment]
My platform is Linux with gcc / gfortran compilers.
```shell
Backtrace for this error:
#0  0x7f962a11dad0 in ???
#1  0x7f962a11cc35 in ???
#2  0x7f9629e2d51f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x55e08ab4635c in __lancelot_precn_double_MOD_precn_use_preconditioner
	at /home/alexis/Bureau/git/GALAHAD/objects/pc64.lnx.gfo/double/precn.f90:931
#4  0x55e08aaf3bbe in lancelot_solve_main
	at /home/alexis/Bureau/git/GALAHAD/objects/pc64.lnx.gfo/double/lancelot.f90:3844
#5  0x55e08ab0c111 in __lancelot_double_MOD_lancelot_solve
	at /home/alexis/Bureau/git/GALAHAD/objects/pc64.lnx.gfo/double/lancelot.f90:1812
#6  0x55e08aae4350 in lancelot_test_deck
	at /home/alexis/Bureau/git/GALAHAD/objects/pc64.lnx.gfo/double/lancelott.f90:1017
#7  0x55e08aae87d3 in main
	at /home/alexis/Bureau/git/GALAHAD/objects/pc64.lnx.gfo/double/lancelott.f90:689
Segmentation fault (core dumped)
 Tests for LANCELOT B complete
```
