### ISSUE TITLE
Errors with fdcti in single precision 

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#51]
We have random segmentation faults with this test.
```
aalexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ ./fdcti_single

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7fb7f5854ad0 in ???
#1  0x7fb7f5853c35 in ???
#2  0x7fb7f564b51f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7fb7f5fbe184 in __galahad_fdc_single_MOD_fdc_find_dependent_rows
	at ../src/fdc/fdc.F90:1774
#4  0x55ef88e8edd1 in galahad_fdc_test
	at ../src/fdc/fdcti.F90:22
#5  0x55ef88e8f035 in main
	at ../src/fdc/fdcti.F90:4
Erreur de segmentation (core dumped)
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ ./fdcti_single

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f05a2552ad0 in ???
#1  0x7f05a2551c35 in ???
#2  0x7f05a234951f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7f05a2cbc184 in __galahad_fdc_single_MOD_fdc_find_dependent_rows
	at ../src/fdc/fdc.F90:1774
#4  0x564b8732ddd1 in galahad_fdc_test
	at ../src/fdc/fdcti.F90:22
#5  0x564b8732e035 in main
	at ../src/fdc/fdcti.F90:4
Erreur de segmentation (core dumped)
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ ./fdcti_single

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f26c4cf7ad0 in ???
#1  0x7f26c4cf6c35 in ???
#2  0x7f26c4aee51f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7f26c5461184 in __galahad_fdc_single_MOD_fdc_find_dependent_rows
	at ../src/fdc/fdc.F90:1774
#4  0x559287e17dd1 in galahad_fdc_test
	at ../src/fdc/fdcti.F90:22
#5  0x559287e18035 in main
	at ../src/fdc/fdcti.F90:4
Erreur de segmentation (core dumped)
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ ./fdcti_single
 FDC_find_dependent exit status =     -9
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ ./fdcti_single
 FDC_find_dependent exit status =     -9
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ ./fdcti_single
 FDC_find_dependent exit status =     -9
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ ./fdcti_single
 FDC_find_dependent exit status =     -9
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ ./fdcti_single
 FDC_find_dependent exit status =     -9
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ ./fdcti_single
 FDC_find_dependent exit status =     -9
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ ./fdcti_single
 FDC_find_dependent exit status =     -9
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ ./fdcti_single

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7fc9ef394ad0 in ???
#1  0x7fc9ef393c35 in ???
#2  0x7fc9ef18b51f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7fc9efafe184 in __galahad_fdc_single_MOD_fdc_find_dependent_rows
	at ../src/fdc/fdc.F90:1774
#4  0x55dd62dffdd1 in galahad_fdc_test
	at ../src/fdc/fdcti.F90:22
#5  0x55dd62e00035 in main
	at ../src/fdc/fdcti.F90:4
^[[AErreur de segmentation (core dumped)
alexis@HP-Spectre:~/Bureau/git/GALAHAD/builddir$ ./fdcti_single
 FDC_find_dependent exit status =     -9

```

**Comment by nimgould** [comment]
This is simply that single precision is insufficient to find dependent constraints.  I have added a check not to evaluated the offending statement above if this happens.
